const WHEELS={
 european:['0','32','15','19','4','21','2','25','17','34','6','27','13','36','11','30','8','23','10','5','24','16','33','1','20','14','31','9','22','18','29','7','28','12','35','3','26'],
 american:['0','28','9','26','30','11','7','20','32','17','5','22','34','15','3','24','36','13','1','00','27','10','25','29','12','8','19','31','18','6','21','33','16','4','23','35','14','2']
};
const RED=new Set(['1','3','5','7','9','12','14','16','18','19','21','23','25','27','30','32','34','36']);
const KEY='brr.phase1.v1';
let store=load(),type=null,centers=[],neighbors=3,locked=null,historyLimit=50;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||base()}catch{return base()}}
function base(){return{european:{results:[],rounds:[]},american:{results:[],rounds:[]}}}
function save(){localStorage.setItem(KEY,JSON.stringify(store))}
if(!store.european.results.length&&Array.isArray(window.BR_DEMO_EUROPEAN_500)&&window.BR_DEMO_EUROPEAN_500.length===500){store.european.results=[...window.BR_DEMO_EUROPEAN_500];save()}
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function color(n){return n==='0'||n==='00'?'green':RED.has(n)?'red':'black'}
function valid(n,t=type){return WHEELS[t].includes(String(n))}
function covered(){const w=WHEELS[type],out=new Set();centers.forEach(c=>{let i=w.indexOf(c);for(let d=-neighbors;d<=neighbors;d++)out.add(w[(i+d+w.length)%w.length])});return out}
function enter(t){type=t;localStorage.setItem('brr.type',t);$('#typeGate').classList.add('hidden');$('#app').classList.remove('hidden');centers=[];locked=null;renderAll()}
function renderAll(){
 $('#rouletteLabel').textContent=type==='american'?'AMERICANA':'EUROPEA';
 $('#mathProbability').textContent=`1 número: ${(100/WHEELS[type].length).toFixed(2)}%`;
 renderNeighbors();renderTrack();renderHistory();renderSignal();renderStats();renderRound();
}
function renderNeighbors(){const el=$('#neighborOptions');el.innerHTML=[0,1,2,3,4].map(n=>`<button class="${n===neighbors?'active':''}" data-n="${n}">${n?'±'+n:'SOLO'}</button>`).join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(locked)return;neighbors=+b.dataset.n;renderNeighbors();renderTrack()})}
function numberButton(n){const cov=covered();return `<button class="number ${color(n)} ${cov.has(n)?'covered':''} ${centers.includes(n)?'center':''}" data-number="${n}"><span>${n}</span></button>`}
function wheelMarkup(){const zero=type==='american'?['0','00']:['0'];return `<div class="zero-key ${type}">${zero.map(numberButton).join('')}</div><div class="table-keys">${Array.from({length:36},(_,i)=>numberButton(String(i+1))).join('')}</div>`}
function marketData(n){if(n==='0'||n==='00')return['VERDE','SIN PARIDAD','CERO','SIN DOCENA','SIN COLUMNA'];const x=+n;return[color(n)==='red'?'ROJO':'NEGRO',x%2?'IMPAR':'PAR',x<=18?'1–18':'19–36',`${Math.ceil(x/12)}ª DOCENA`,`${((x-1)%3)+1}ª COLUMNA`]}
function renderMarket(n){$('#marketSummary').innerHTML=marketData(n).map(x=>`<span>${x}</span>`).join('')}
function renderTrack(){$('#racetrack').innerHTML=wheelMarkup();$('#racetrack').querySelectorAll('button[data-number]').forEach(b=>b.onclick=()=>{$('#resultInput').value=b.dataset.number;freezeRound();renderMarket(b.dataset.number);$('#racetrack').querySelectorAll('.number').forEach(x=>x.classList.toggle('picked',x.dataset.number===b.dataset.number))})}
function toggleCenter(n){if(locked)return;if(centers.includes(n))centers=centers.filter(x=>x!==n);else if(centers.length<3)centers.push(n);renderTrack()}
function demoScores(){const arr=store[type].results;if(!arr.length)return[];const w=WHEELS[type],recent=arr.slice(-25),wide=arr.slice(-100);return w.map((n,i)=>{let f=recent.filter(x=>x===n).length/(recent.length||1),g=wide.filter(x=>x===n).length/(wide.length||1);let sector=recent.reduce((s,x)=>{let j=w.indexOf(x),d=Math.min(Math.abs(i-j),w.length-Math.abs(i-j));return s+(d<=3?1:0)},0)/(recent.length||1);return{n,score:Math.round(Math.min(99,35+f*250+Math.max(0,f-g)*180+sector*45))}}).sort((a,b)=>b.score-a.score||w.indexOf(a.n)-w.indexOf(b.n)).slice(0,3)}
function renderSignal(){const s=locked?locked.signal:demoScores();$('#signals').innerHTML=(s.length?s:[{n:'—'},{n:'—'},{n:'—'}]).map((x,i)=>`<div class="signal"><small>0${i+1}</small>${x.n}</div>`).join('');$('#confidence').textContent=s.length?'DEMO · NO CALIBRADA':'SIN DATOS';$('#signalNote').textContent=s.length?'Ranking provisional de interfaz; no es el BR Engine real ni una garantía.':'Importa resultados reales para activar la demostración estadística.'}
function renderHistory(){const arr=store[type].results;$('#recentResults').innerHTML=arr.slice(-12).reverse().map(n=>`<div class="ball ${color(n)}">${n}</div>`).join('')||'<small>Sin resultados cargados</small>';$('#historyFilters').innerHTML=[25,50,100,250,500,'all'].map(n=>`<button class="${historyLimit===n?'active':''}" data-limit="${n}">${n==='all'?'TODO':n}</button>`).join('');$('#historyFilters').querySelectorAll('button').forEach(b=>b.onclick=()=>{historyLimit=b.dataset.limit==='all'?'all':+b.dataset.limit;renderHistory()});const shown=historyLimit==='all'?arr:arr.slice(-historyLimit);$('#historyGrid').innerHTML=shown.slice().reverse().map(n=>`<div class="ball ${color(n)}">${n}</div>`).join('')||'<p>No hay resultados. Importa un JSON real.</p>'}
function freezeRound(){if(locked)return true;const signal=demoScores();locked={timestamp:new Date().toISOString(),historySize:store[type].results.length,signal,scores:signal,candidates:signal.map(x=>x.n)};return true}
function renderRound(){const btn=$('#lockBtn');btn.textContent='REGISTRAR';btn.classList.toggle('locked',!!locked);$('#resultInput').disabled=false;$('#resultInput').placeholder=type==='american'?'0 / 00 / 1–36':'0–36';if(locked)$('#roundStatus').textContent='Propuesta anterior congelada · lista para registrar';renderSignal()}
function lockOrRecord(){const n=$('#resultInput').value.trim();if(!valid(n)){ $('#roundStatus').textContent='Resultado inválido para esta ruleta.';return}freezeRound();const won=locked.candidates.includes(n);store[type].rounds.push({...locked,result:n,outcome:won?'TOP 3':'FUERA TOP 3'});store[type].results.push(n);save();locked=null;centers=[];$('#resultInput').value='';renderAll();renderMarket(n);$('#roundStatus').textContent=won?'ACIERTO TOP 3 · propuesta recalculada.':'FUERA DEL TOP 3 · propuesta recalculada.'}
function renderStats(){const r=store[type].rounds,wins=r.filter(x=>x.outcome==='TOP 3'||x.outcome==='GANADO').length;const vals=[['GIROS ANALIZADOS',store[type].results.length],['SEÑALES GENERADAS',r.length],['ACIERTOS TOP 3',wins],['FUERA TOP 3',r.length-wins],['% TOP 3',r.length?(wins/r.length*100).toFixed(1)+'%':'—'],['MUESTRA BASE',store[type].results.length]];$('#statsGrid').innerHTML=vals.map(x=>`<div class="stat"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')}
function importJSON(){try{const d=JSON.parse($('#jsonInput').value),t=d.roulette;if(!WHEELS[t]||!Array.isArray(d.results))throw Error('Formato no reconocido.');const vals=d.results.map(String);const bad=vals.filter(n=>!valid(n,t));if(bad.length)throw Error(`Valores inválidos: ${[...new Set(bad)].join(', ')}`);if(t!==type)throw Error(`Este JSON es ${t}; cambia primero el tipo de ruleta.`);store[type].results.push(...vals);save();$('#importStatus').textContent=`Importados ${vals.length} resultados sin alterar el orden recibido.`;$('#jsonInput').value='';renderAll()}catch(e){$('#importStatus').textContent='No importado: '+e.message}}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));closeMenu();scrollTo(0,0)}
function closeMenu(){$('#drawer').classList.remove('open');$('#scrim').classList.remove('open')}
$$('[data-type]').forEach(b=>b.onclick=()=>enter(b.dataset.type));$('#changeTypeBtn').onclick=()=>{$('#app').classList.add('hidden');$('#typeGate').classList.remove('hidden')};$('#resultInput').addEventListener('input',e=>{const n=e.target.value.trim();if(valid(n))renderMarket(n)});$('#resultInput').addEventListener('focus',freezeRound);$('#resultInput').addEventListener('keydown',e=>{if(e.key==='Enter')lockOrRecord()});$('#lockBtn').onclick=lockOrRecord;$('#importBtn').onclick=importJSON;$('#menuBtn').onclick=()=>{$('#drawer').classList.add('open');$('#scrim').classList.add('open')};$('#scrim').onclick=closeMenu;$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({roulette:type,...store[type]},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`black-royal-${type}-backup.json`;a.click();URL.revokeObjectURL(a.href)};$('#resetBtn').onclick=()=>{if(confirm('¿Borrar todos los datos locales de esta ruleta?')){store[type]=base()[type];save();renderAll()}};
const remembered=localStorage.getItem('brr.type');if(remembered&&WHEELS[remembered])enter(remembered);
