// BLACK ROYAL — importación de historial desde capturas (cliente, sin subir imágenes al servidor)
let brOcrDraft=[];
function brLoadImage(file){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=URL.createObjectURL(file)})}
function brPrepareCrops(img){
 const specs=[[0,.06,.30,.92],[0,.08,.36,.88],[0,.12,.42,.82],[0,0,.50,1],[0,0,1,1]];
 return specs.map(([xf,yf,wf,hf])=>{const sx=Math.round(img.width*xf),sy=Math.round(img.height*yf),sw=Math.max(1,Math.round(img.width*wf)),sh=Math.max(1,Math.round(img.height*hf));const scale=Math.min(3.2,2200/sw);const c=document.createElement('canvas');c.width=Math.round(sw*scale);c.height=Math.round(sh*scale);const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,sx,sy,sw,sh,0,0,c.width,c.height);return c})
}
function brNumbersFromText(text){
 // Tesseract frecuentemente pone cada celda en una línea distinta. Antes exigíamos 4+ números por línea,
 // lo que descartaba casi toda la cuadrícula. Ahora conservamos todos los tokens 0–36 en orden de lectura.
 return (String(text||'').match(/\b\d{1,3}\b/g)||[]).map(v=>String(Number(v))).filter(v=>Number(v)>=0&&Number(v)<=36)
}
function brOverlap(a,b,max=120){const lim=Math.min(max,a.length,b.length);for(let n=lim;n>=4;n--)if(a.slice(-n).every((v,i)=>v===b[i]))return n;return 0}
function brJoinSegments(segments){let joined=[];for(const seg0 of segments.filter(x=>x.length)){const seg=[...seg0];if(!joined.length){joined=seg;continue}const ab=brOverlap(joined,seg),ba=brOverlap(seg,joined);if(ab>=ba&&ab){joined.push(...seg.slice(ab));continue}if(ba){joined=[...seg,...joined.slice(ba)];continue}joined.push(...seg)}return joined}
function brRenderOcrPreview(){const box=document.querySelector('#ocrPreview'),info=document.querySelector('#ocrInfo');if(!box||!info)return;box.value=brOcrDraft.join(', ');info.textContent=brOcrDraft.length?`Detectados ${brOcrDraft.length} resultados · revisa antes de guardar.`:'No se detectaron resultados todavía.';document.querySelector('#ocrConfirmBtn')?.classList.toggle('hidden',!brOcrDraft.length)}
async function brRecognize(canvas,logger){
 const result=await Tesseract.recognize(canvas,'eng',{logger,tessedit_char_whitelist:'0123456789 ',preserve_interword_spaces:'1',tessedit_pageseg_mode:'11'});
 return brNumbersFromText(result?.data?.text)
}
async function brReadScreenshots(){const input=document.querySelector('#historyImages'),status=document.querySelector('#ocrStatus'),files=[...(input?.files||[])];if(!files.length){status.textContent='Selecciona una o varias capturas.';return}if(typeof Tesseract==='undefined'){status.textContent='No se pudo cargar el lector de imágenes. Revisa tu conexión e inténtalo otra vez.';return}const btn=document.querySelector('#ocrReadBtn');if(btn)btn.disabled=true;try{const segments=[];for(let i=0;i<files.length;i++){status.textContent=`Analizando captura ${i+1} de ${files.length}…`;const img=await brLoadImage(files[i]),crops=brPrepareCrops(img);let best=[];for(let c=0;c<crops.length;c++){status.textContent=`Captura ${i+1}/${files.length} · buscando cuadrícula ${c+1}/${crops.length}…`;const vals=await brRecognize(crops[c],m=>{if(m.status==='recognizing text')status.textContent=`Captura ${i+1}/${files.length} · lectura ${Math.round((m.progress||0)*100)}%`});if(vals.length>best.length)best=vals;if(best.length>=140)break}segments.push(best)}brOcrDraft=brJoinSegments(segments);brRenderOcrPreview();status.textContent=brOcrDraft.length?`Lectura terminada. ${brOcrDraft.length} números encontrados. Revísalos antes de guardar.`:'No pude detectar la cuadrícula. Recorta la captura dejando visible el panel “Últimos resultados”.'}catch(e){console.error(e);status.textContent='No pude leer esa captura. Prueba con la imagen original o recórtala dejando sólo “Últimos resultados”.'}finally{if(btn)btn.disabled=false}}
function brConfirmOcr(){const box=document.querySelector('#ocrPreview'),status=document.querySelector('#ocrStatus');let vals=parseBulk(box.value).filter(v=>valid(v));if(vals.length<2){status.textContent='Revisa la lista: necesito al menos 2 números válidos.';return}if(document.querySelector('#ocrOrder')?.value==='newest')vals.reverse();const mode=document.querySelector('#ocrMode')?.value||'replace';if(mode==='replace')store[type]={results:vals,rounds:[]};else store[type].results.push(...vals);save();locked=null;centers=[];historyLimit=50;renderAll();status.textContent=`Historial ${mode==='replace'?'reemplazado':'actualizado'} con ${vals.length} resultados · último ${store[type].results.at(-1)}.`;brOcrDraft=[];box.value='';document.querySelector('#historyImages').value='';document.querySelector('#ocrConfirmBtn')?.classList.add('hidden')}
document.querySelector('#ocrReadBtn')?.addEventListener('click',brReadScreenshots);document.querySelector('#ocrConfirmBtn')?.addEventListener('click',brConfirmOcr);document.querySelector('#ocrPreview')?.addEventListener('input',e=>{brOcrDraft=parseBulk(e.target.value).filter(v=>valid(v));document.querySelector('#ocrInfo').textContent=`Lista editada · ${brOcrDraft.length} números válidos.`});