const BRW={european:['0','32','15','19','4','21','2','25','17','34','6','27','13','36','11','30','8','23','10','5','24','16','33','1','20','14','31','9','22','18','29','7','28','12','35','3','26'],american:['0','28','9','26','30','11','7','20','32','17','5','22','34','15','3','24','36','13','1','00','27','10','25','29','12','8','19','31','18','6','21','33','16','4','23','35','14','2']};
const BRRED=new Set(['1','3','5','7','9','12','14','16','18','19','21','23','25','27','30','32','34','36']);
const KEY='brr.v10.tables';const TYPEKEY='brr.type';let rouletteType='european';let activeTable='t1';let selectedResult=null;let db=loadDB();
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function clone(v){return JSON.parse(JSON.stringify(v))}
function seedMain(){const a=Array.isArray(window.BR_SESSION_EUROPEAN_500)?window.BR_SESSION_EUROPEAN_500:[];const b=Array.isArray(window.BR_SESSION_EUROPEAN_APPEND)?window.BR_SESSION_EUROPEAN_APPEND:[];const c=a.length?[...a,...b]:(Array.isArray(window.BR_DEMO_EUROPEAN_500)?window.BR_DEMO_EUROPEAN_500:[]);return c.map(String)}
function loadLegacy(){try{const old=JSON.parse(localStorage.getItem('brr.european.tables.v1'));if(old?.tables){return{t1:{name:old.tables.main?.label||'Age of Gods',results:(old.tables.main?.data?.results||seedMain()).map(String),events:[]},t2:{name:old.tables.table2?.label||'Roulette A',results:(old.tables.table2?.data?.results||window.BR_TABLE_2_RESULTS||[]).map(String),events:[]}}}}catch{}return null}
function loadDB(){try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved?.tables)return saved}catch{}const legacy=loadLegacy();return{active:'t1',tables:{t1:legacy?.t1||{name:'Age of Gods',results:seedMain(),events:[]},t2:legacy?.t2||{name:'Roulette A',results:(window.BR_TABLE_2_RESULTS||[]).map(String),events:[]},t3:{name:'Evolution 1',results:[],events:[]},t4:{name:'Casino Sala',results:[],events:[]},t5:{name:'Nueva mesa',results:[],events:[]}}}}
function saveDB(){db.active=activeTable;localStorage.setItem(KEY,JSON.stringify(db))}
function table(){return db.tables[activeTable]}
function color(n){return n==='0'||n==='00'?'green':BRRED.has(String(n))?'red':'black'}
function valid(n){return BRW[rouletteType].includes(String(n))}
function latest(){return table().results.at(-1)||'—'}
function setType(t){rouletteType=t;localStorage.setItem(TYPEKEY,t);$('#typeGate').classList.add('hidden');$('#app').classList.remove('hidden');$('#rouletteLabel').textContent=t==='american'?'Americana':'Europea';if(t==='american'){$('#tablesBlock').classList.add('hidden')}else{$('#tablesBlock').classList.remove('hidden')}selectedResult=null;renderAll()}
function market(n){if(!n||n==='—'||n==='0'||n==='00')return{color:null,parity:null,range:null,dozen:null,column:null};const x=+n;return{color:color(n),parity:x%2?'odd':'even',range:x<=18?'low':'high',dozen:String(Math.ceil(x/12)),column:String(((x-1)%3)+1)}}
function scoreBinary(arr,test,expected=.5){const sample=arr.slice(-36);if(sample.length<18)return{choice:null,strength:0};const hit=sample.filter(test).length;const p=hit/sample.length;const diff=Math.abs(p-expected);return{choice:p>=expected?1:0,strength:diff,sample:sample.length,p}}
function activeMarkets(){const arr=table().results.filter(n=>n!=='0'&&n!=='00');const c=scoreBinary(arr,n=>color(n)==='red');const p=scoreBinary(arr,n=>(+n)%2===0);const r=scoreBinary(arr,n=>(+n)<=18);const last=arr.slice(-36);const dozen=[1,2,3].map(d=>last.filter(n=>Math.ceil(+n/12)===d).length);const col=[1,2,3].map(c=>last.filter(n=>((+n-1)%3)+1===c).length);const maxD=Math.max(...dozen,0),maxC=Math.max(...col,0);const dChoice=last.length>=24&&maxD/last.length>=.43?String(dozen.indexOf(maxD)+1):null;const cChoice=last.length>=24&&maxC/last.length>=.43?String(col.indexOf(maxC)+1):null;return{color:c.strength>=.14?(c.choice?'red':'black'):null,parity:p.strength>=.14?(p.choice?'even':'odd'):null,range:r.strength>=.14?(r.choice?'low':'high'):null,dozen:dChoice,column:cChoice}}
function demoScores(){const arr=table().results;if(arr.length<10)return[];const wheel=BRW[rouletteType],recent=arr.slice(-25),wide=arr.slice(-100),last=arr.at(-1);const trans=new Map();let transTotal=0;for(let i=0;i<arr.length-1;i++)if(arr[i]===last){trans.set(arr[i+1],(trans.get(arr[i+1])||0)+1);transTotal++}return wheel.map((n,i)=>{const f=recent.filter(x=>x===n).length/(recent.length||1),g=wide.filter(x=>x===n).length/(wide.length||1),t=(trans.get(n)||0)/(transTotal||1);const sector=recent.reduce((s,x)=>{const j=wheel.indexOf(x),d=Math.min(Math.abs(i-j),wheel.length-Math.abs(i-j));return s+(d<=3?1:0)},0)/(recent.length||1);const li=wheel.indexOf(last),dist=Math.min(Math.abs(i-li),wheel.length-Math.abs(i-li)),physical=dist<=4?(5-dist)/5:0;return{n,score:30+f*180+Math.max(0,f-g)*120+sector*30+t*240+physical*18}}).sort((a,b)=>b.score-a.score||wheel.indexOf(a.n)-wheel.indexOf(b.n)).slice(0,3)}
function recentChip(n,latest=false){return `<span class="recent-chip ${color(n)} ${latest?'latest':''}">${n}</span>`}
function renderRecent(){const arr=table().results.slice(-25).reverse();$('#recent25').innerHTML=arr.map((n,i)=>recentChip(n,i===0)).join('')||'<span class="recent-chip latest">—</span>'}
function renderLast(){const arr=table().results;$('#lastNumber').textContent=arr.at(-1)||'—';$('#lastFive').innerHTML=arr.slice(-5).reverse().map(n=>recentChip(n)).join('')}
function setSig(selector,on){const el=$(selector);if(el)el.classList.toggle('active',!!on)}
function renderMarketSignals(){const s=activeMarkets();$$('.sig').forEach(x=>x.classList.remove('active'));setSig('#sigRed',s.color==='red');setSig('#sigBlack',s.color==='black');setSig('#sigEven',s.parity==='even');setSig('#sigOdd',s.parity==='odd');setSig('#sigLow',s.range==='low');setSig('#sigHigh',s.range==='high');['1','2','3'].forEach(x=>setSig('#sigDozen'+x,s.dozen===x));['1','2','3'].forEach(x=>setSig('#sigCol'+x,s.column===x));const any=!!(s.color||s.parity||s.range||s.dozen||s.column);$('#noSignal').classList.toggle('active',!any)}
function renderCandidates(){const c=demoScores();$('#candidateRow').innerHTML=[0,1,2].map(i=>c[i]?`<div class="candidate">${c[i].n}<small>±3</small></div>`:'<div class="candidate">—</div>').join('')}
function renderTables(){const wrap=$('#tableList');if(!wrap)return;wrap.innerHTML=Object.entries(db.tables).map(([id,t],i)=>`<div class="table-slot ${id===activeTable?'active':''}"><button class="table-select" data-table="${id}"><b>0${i+1}</b><span>${escapeHTML(t.name)}</span><small>${t.results.length?`${t.results.length} tiradas`:'Vacía'}</small></button><button class="rename" data-rename="${id}" aria-label="Renombrar mesa">✎</button></div>`).join('');$$('[data-table]').forEach(b=>b.addEventListener('click',()=>{activeTable=b.dataset.table;selectedResult=null;saveDB();renderAll()}));$$('[data-rename]').forEach(b=>b.addEventListener('click',()=>renameTable(b.dataset.rename)))}
function renameTable(id){const old=db.tables[id].name;const name=prompt('Nombre de la mesa',old);if(name&&name.trim()){db.tables[id].name=name.trim().slice(0,32);saveDB();renderTables()}}
function numButton(n){return `<button type="button" class="number ${color(n)}" data-number="${n}"><span>${n}</span></button>`}
function renderBoard(){const zero=rouletteType==='american'?['0','00']:['0'];$('#racetrack').innerHTML=`<div class="zero-key ${rouletteType}">${zero.map(numButton).join('')}</div><div class="table-keys">${Array.from({length:36},(_,i)=>numButton(String(i+1))).join('')}</div>`;$$('#racetrack [data-number]').forEach(b=>b.addEventListener('click',()=>selectNumber(b.dataset.number)));refreshPicked()}
function selectNumber(n){selectedResult=n;refreshPicked();$('#registerBtn').disabled=false;$('#registerBtn').textContent=`✓ Registrar ${n}`}
function refreshPicked(){$$('#racetrack .number').forEach(b=>b.classList.toggle('picked',b.dataset.number===selectedResult))}
function registerSelected(){if(!selectedResult||!valid(selectedResult))return;const n=selectedResult;table().results.push(n);table().events=table().events||[];table().events.push({n,at:new Date().toISOString()});selectedResult=null;saveDB();renderAll();toast(`Resultado ${n} registrado`)}
function renderHistory(){const grid=$('#historyGrid');if(!grid)return;const t=table(),events=t.events||[];if(events.length){const grouped={};events.slice().reverse().forEach(e=>{const d=new Date(e.at).toLocaleDateString('es-MX',{day:'2-digit',month:'short',year:'numeric'});(grouped[d]??=[]).push(e.n)});grid.innerHTML=Object.entries(grouped).map(([d,nums])=>`<div class="day-label">${d}</div>${nums.map(n=>`<div class="history-ball ${color(n)}">${n}</div>`).join('')}`).join('')}else{grid.innerHTML=t.results.slice().reverse().map(n=>`<div class="history-ball ${color(n)}">${n}</div>`).join('')||'<p>Esta mesa todavía no tiene resultados.</p>'}$('#historyTitle').textContent=t.name}
function renderAll(){renderRecent();renderLast();renderMarketSignals();renderCandidates();renderTables();renderBoard();renderHistory();$('#registerBtn').disabled=!selectedResult;$('#registerBtn').textContent=selectedResult?`✓ Registrar ${selectedResult}`:'✓ Registrar'}
function showView(id){$('#liveView').classList.toggle('hidden',id!=='live');$('#historyView').classList.toggle('hidden',id!=='history');$('#captureView').classList.toggle('hidden',id!=='capture');$('#settingsView').classList.toggle('hidden',id!=='settings');if(id==='history')renderHistory();scrollTo({top:0,behavior:'smooth'})}
function importBulk(){const raw=$('#bulkResults').value;let vals=raw.split(/[\s,;→]+/).map(v=>v.trim()).filter(Boolean).map(v=>v==='00'?'00':/^\d+$/.test(v)?String(Number(v)):v);if($('#bulkOrder').value==='newest')vals.reverse();const bad=vals.filter(n=>!valid(n));if(vals.length<2||vals.length>500||bad.length){$('#bulkStatus').textContent=bad.length?`Valores inválidos: ${[...new Set(bad)].join(', ')}`:'Usa entre 2 y 500 resultados.';return}if(!confirm(`Reemplazar el historial de ${table().name} con ${vals.length} resultados?`))return;table().results=vals;table().events=[];saveDB();$('#bulkResults').value='';$('#bulkStatus').textContent=`Historial actualizado: ${vals.length} tiradas.`;renderAll()}
function exportJSON(){const blob=new Blob([JSON.stringify({version:'V10',type:rouletteType,activeTable,tables:db.tables},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='black-royal-roulette-v10.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function resetTable(){if(confirm(`¿Borrar todos los datos de ${table().name}?`)){table().results=[];table().events=[];selectedResult=null;saveDB();renderAll();toast('Mesa vaciada')}}
function escapeHTML(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
let toastTimer;function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1600)}
function bind(){$$('[data-type]').forEach(b=>b.addEventListener('click',()=>setType(b.dataset.type)));$('#registerBtn').addEventListener('click',registerSelected);$('#historyBtn').addEventListener('click',()=>showView('history'));$('#captureBtn').addEventListener('click',()=>showView('capture'));$$('[data-back]').forEach(b=>b.addEventListener('click',()=>showView('live')));$('#settingsBtn').addEventListener('click',()=>showView('settings'));$('#bulkImportBtn').addEventListener('click',importBulk);$('#exportBtn').addEventListener('click',exportJSON);$('#resetBtn').addEventListener('click',resetTable)}
activeTable=db.active&&db.tables[db.active]?db.active:'t1';bind();const remembered=localStorage.getItem(TYPEKEY);if(remembered&&BRW[remembered])setType(remembered);